# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.0/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/lyndseygu/clionprojects/black-scholes-cxx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/lyndseygu/clionprojects/black-scholes-cxx

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.27.0/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lyndseygu/clionprojects/black-scholes-cxx/CMakeFiles /Users/lyndseygu/clionprojects/black-scholes-cxx//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/lyndseygu/clionprojects/black-scholes-cxx/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blackScholesLibrary

# Build rule for target.
blackScholesLibrary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blackScholesLibrary
.PHONY : blackScholesLibrary

# fast build rule for target.
blackScholesLibrary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/build
.PHONY : blackScholesLibrary/fast

#=============================================================================
# Target rules for targets named black_scholes_cpp

# Build rule for target.
black_scholes_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 black_scholes_cpp
.PHONY : black_scholes_cpp

# fast build rule for target.
black_scholes_cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/build
.PHONY : black_scholes_cpp/fast

#=============================================================================
# Target rules for targets named cleanup

# Build rule for target.
cleanup: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cleanup
.PHONY : cleanup

# fast build rule for target.
cleanup/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cleanup.dir/build.make CMakeFiles/cleanup.dir/build
.PHONY : cleanup/fast

#=============================================================================
# Target rules for targets named run_tests_gtest

# Build rule for target.
run_tests_gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests_gtest
.PHONY : run_tests_gtest

# fast build rule for target.
run_tests_gtest/fast:
	$(MAKE) $(MAKESILENT) -f gtest/CMakeFiles/run_tests_gtest.dir/build.make gtest/CMakeFiles/run_tests_gtest.dir/build
.PHONY : run_tests_gtest/fast

#=============================================================================
# Target rules for targets named blackScholesModelTest

# Build rule for target.
blackScholesModelTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 blackScholesModelTest
.PHONY : blackScholesModelTest

# fast build rule for target.
blackScholesModelTest/fast:
	$(MAKE) $(MAKESILENT) -f gtest/CMakeFiles/blackScholesModelTest.dir/build.make gtest/CMakeFiles/blackScholesModelTest.dir/build
.PHONY : blackScholesModelTest/fast

#=============================================================================
# Target rules for targets named bsm

# Build rule for target.
bsm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bsm
.PHONY : bsm

# fast build rule for target.
bsm/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/bsm.dir/build.make src/CMakeFiles/bsm.dir/build
.PHONY : bsm/fast

#=============================================================================
# Target rules for targets named black_scholes_cpp_test

# Build rule for target.
black_scholes_cpp_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 black_scholes_cpp_test
.PHONY : black_scholes_cpp_test

# fast build rule for target.
black_scholes_cpp_test/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/black_scholes_cpp_test.dir/build.make test/CMakeFiles/black_scholes_cpp_test.dir/build
.PHONY : black_scholes_cpp_test/fast

src/Program.o: src/Program.cpp.o
.PHONY : src/Program.o

# target to build an object file
src/Program.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/Program.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/Program.cpp.o
.PHONY : src/Program.cpp.o

src/Program.i: src/Program.cpp.i
.PHONY : src/Program.i

# target to preprocess a source file
src/Program.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/Program.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/Program.cpp.i
.PHONY : src/Program.cpp.i

src/Program.s: src/Program.cpp.s
.PHONY : src/Program.s

# target to generate assembly for a file
src/Program.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/Program.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/Program.cpp.s
.PHONY : src/Program.cpp.s

src/blackScholesModel.o: src/blackScholesModel.cpp.o
.PHONY : src/blackScholesModel.o

# target to build an object file
src/blackScholesModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/blackScholesModel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/blackScholesModel.cpp.o
.PHONY : src/blackScholesModel.cpp.o

src/blackScholesModel.i: src/blackScholesModel.cpp.i
.PHONY : src/blackScholesModel.i

# target to preprocess a source file
src/blackScholesModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/blackScholesModel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/blackScholesModel.cpp.i
.PHONY : src/blackScholesModel.cpp.i

src/blackScholesModel.s: src/blackScholesModel.cpp.s
.PHONY : src/blackScholesModel.s

# target to generate assembly for a file
src/blackScholesModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/blackScholesModel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/blackScholesModel.cpp.s
.PHONY : src/blackScholesModel.cpp.s

src/hestonModel.o: src/hestonModel.cpp.o
.PHONY : src/hestonModel.o

# target to build an object file
src/hestonModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/hestonModel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/hestonModel.cpp.o
.PHONY : src/hestonModel.cpp.o

src/hestonModel.i: src/hestonModel.cpp.i
.PHONY : src/hestonModel.i

# target to preprocess a source file
src/hestonModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/hestonModel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/hestonModel.cpp.i
.PHONY : src/hestonModel.cpp.i

src/hestonModel.s: src/hestonModel.cpp.s
.PHONY : src/hestonModel.s

# target to generate assembly for a file
src/hestonModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/hestonModel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/hestonModel.cpp.s
.PHONY : src/hestonModel.cpp.s

src/inputReader.o: src/inputReader.cpp.o
.PHONY : src/inputReader.o

# target to build an object file
src/inputReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/inputReader.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/inputReader.cpp.o
.PHONY : src/inputReader.cpp.o

src/inputReader.i: src/inputReader.cpp.i
.PHONY : src/inputReader.i

# target to preprocess a source file
src/inputReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/inputReader.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/inputReader.cpp.i
.PHONY : src/inputReader.cpp.i

src/inputReader.s: src/inputReader.cpp.s
.PHONY : src/inputReader.s

# target to generate assembly for a file
src/inputReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/inputReader.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/inputReader.cpp.s
.PHONY : src/inputReader.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/optionGreeks.o: src/optionGreeks.cpp.o
.PHONY : src/optionGreeks.o

# target to build an object file
src/optionGreeks.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/optionGreeks.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/optionGreeks.cpp.o
.PHONY : src/optionGreeks.cpp.o

src/optionGreeks.i: src/optionGreeks.cpp.i
.PHONY : src/optionGreeks.i

# target to preprocess a source file
src/optionGreeks.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/optionGreeks.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/optionGreeks.cpp.i
.PHONY : src/optionGreeks.cpp.i

src/optionGreeks.s: src/optionGreeks.cpp.s
.PHONY : src/optionGreeks.s

# target to generate assembly for a file
src/optionGreeks.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/optionGreeks.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/optionGreeks.cpp.s
.PHONY : src/optionGreeks.cpp.s

src/optionGreeksModel.o: src/optionGreeksModel.cpp.o
.PHONY : src/optionGreeksModel.o

# target to build an object file
src/optionGreeksModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/optionGreeksModel.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/optionGreeksModel.cpp.o
.PHONY : src/optionGreeksModel.cpp.o

src/optionGreeksModel.i: src/optionGreeksModel.cpp.i
.PHONY : src/optionGreeksModel.i

# target to preprocess a source file
src/optionGreeksModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/optionGreeksModel.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/optionGreeksModel.cpp.i
.PHONY : src/optionGreeksModel.cpp.i

src/optionGreeksModel.s: src/optionGreeksModel.cpp.s
.PHONY : src/optionGreeksModel.s

# target to generate assembly for a file
src/optionGreeksModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/optionGreeksModel.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/optionGreeksModel.cpp.s
.PHONY : src/optionGreeksModel.cpp.s

src/outputWriter.o: src/outputWriter.cpp.o
.PHONY : src/outputWriter.o

# target to build an object file
src/outputWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/outputWriter.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/outputWriter.cpp.o
.PHONY : src/outputWriter.cpp.o

src/outputWriter.i: src/outputWriter.cpp.i
.PHONY : src/outputWriter.i

# target to preprocess a source file
src/outputWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/outputWriter.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/outputWriter.cpp.i
.PHONY : src/outputWriter.cpp.i

src/outputWriter.s: src/outputWriter.cpp.s
.PHONY : src/outputWriter.s

# target to generate assembly for a file
src/outputWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/blackScholesLibrary.dir/build.make CMakeFiles/blackScholesLibrary.dir/src/outputWriter.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/black_scholes_cpp.dir/build.make CMakeFiles/black_scholes_cpp.dir/src/outputWriter.cpp.s
.PHONY : src/outputWriter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... cleanup"
	@echo "... blackScholesLibrary"
	@echo "... blackScholesModelTest"
	@echo "... black_scholes_cpp"
	@echo "... black_scholes_cpp_test"
	@echo "... bsm"
	@echo "... run_tests_gtest"
	@echo "... src/Program.o"
	@echo "... src/Program.i"
	@echo "... src/Program.s"
	@echo "... src/blackScholesModel.o"
	@echo "... src/blackScholesModel.i"
	@echo "... src/blackScholesModel.s"
	@echo "... src/hestonModel.o"
	@echo "... src/hestonModel.i"
	@echo "... src/hestonModel.s"
	@echo "... src/inputReader.o"
	@echo "... src/inputReader.i"
	@echo "... src/inputReader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/optionGreeks.o"
	@echo "... src/optionGreeks.i"
	@echo "... src/optionGreeks.s"
	@echo "... src/optionGreeksModel.o"
	@echo "... src/optionGreeksModel.i"
	@echo "... src/optionGreeksModel.s"
	@echo "... src/outputWriter.o"
	@echo "... src/outputWriter.i"
	@echo "... src/outputWriter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

